apiVersion: v1
kind: Pod
metadata:
  namespace: akv-test
  name: sidecarclient
  labels:
    aadpodidbinding: akv-test
spec:
  containers:
    - name: sidecarclient
      image: dsanabria/client_sidecar
      env:
      - name: client_id
        value: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /token
          name: token
    - name: psqlconnector
      image: dsanabria/psqltest:latest
      args:
        - "sleep"
        - "10000"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /token
          name: token
  volumes:
    - name: token
      emptyDir:
        medium: Memory
