apiVersion: v1
kind: Pod
metadata:
  namespace: svc-reliability-sandbox
  name: sidecarclient
  labels:
    aadpodidbinding: svc-reliability-nonprod
spec:
  containers:
    - name: sidecarclient
      image: dsanabria/client_sidecar
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /token
          name: token
    - name: psqlconnector
      image: dsanabria/psqltest:latest
      args:
        - "sleep"
        - "10000"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /token
          name: token
  volumes:
    - name: token
      emptyDir:
        medium: Memory
